import type { DocumentItem } from '../types/document';
import { DocRendererService } from './docRenderer';

export const SAMPLE_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc-1',
    title: '2024년 인공지능 기반 서비스 사업계획서',
    fileName: '2024_AI_Business_Plan_v2.1.pdf',
    fileSize: 4850000,
    format: 'pdf',
    dateCreated: '2024-02-15',
    dateModified: '2024-06-20',
    pageCount: 42,
    thumbnailUrl: DocRendererService.generateDocumentFirstPageThumbnail(
      '2024년 인공지능 기반 서비스 사업계획서',
      'pdf',
      '📊 사업계획서 / 제안서',
      '본 사업계획서는 생성형 AI 및 온디바이스 컴퓨터 비전 기술을 결합하여 차세대 생산성 소프트웨어를 구축하고 글로벌 시장 진출을 위한 전략적 로드맵을 제시합니다.',
      '2024-02-15',
      '전략기획본부'
    ),
    extractedText: '2024년 인공지능 기반 서비스 사업계획서\n1. 사업 개요 및 시장 기회\n최근 AI 모델의 고속화와 경량화에 힘입어 클라우드 의존도를 낮춘 온디바이스 AI 시장이 연평균 38% 성장하고 있습니다. 당사는 로컬 프라이버시 보호와 초고속 인덱싱 엔진을 무기로 엔터프라이즈 및 개인용 시각 솔루션을 개발합니다.\n2. 비즈니스 모델 및 수익화 방안\n- B2C 프리미엄 구독 모델 (월 9,900원)\n- B2B 온프레미스 기업용 라이선스 공급\n3. 추진 일정 및 재무 목표\n2024년 상반기 베타 런칭 후 유료 전환율 8% 달성 목표.',
    keywords: ['인공지능', '사업계획서', '온디바이스', '비즈니스모델', '투자유치', '로드맵', '성장률'],
    category: '📊 사업계획서 / 제안서',
    folder: '2024 기획 & 제안서',
    isStarred: true,
    author: '전략기획본부 김철수',
    company: '주식회사 알파',
  },
  {
    id: 'doc-2',
    title: '2024년 상반기 재무결산 및 손익계산서',
    fileName: '2024_1H_Financial_Statement.xlsx',
    fileSize: 1820000,
    format: 'xlsx',
    dateCreated: '2024-07-05',
    dateModified: '2024-07-12',
    pageCount: 5,
    thumbnailUrl: DocRendererService.generateDocumentFirstPageThumbnail(
      '2024년 상반기 재무결산 및 손익계산서',
      'xlsx',
      '💰 재무 / 결산 / 예산',
      '2024년 1월부터 6월까지의 부서별 매출액, 영업비용, 당기순이익 및 부가세 신고 내역을 집계한 재무제표 종합 보고서입니다.',
      '2024-07-05',
      '재무회계팀'
    ),
    extractedText: '2024년 상반기 재무결산 보고서\n- 총 매출액: 1,450,000,000원 (전년 동기 대비 +24% 증가)\n- 매출원가: 580,000,000원\n- 판매비와 관리비: 420,000,000원\n- 영업이익: 450,000,000원 (영업이익률 31.0%)\n- 법인세차감전 순이익: 428,000,000원\n주요 지출 항목: 클라우드 서버 인프라 비용, R&D 인건비, 마케팅 광고 집행비.',
    keywords: ['재무제표', '손익계산서', '매출액', '영업이익', '결산', '상반기', '부가세', '회계'],
    category: '💰 재무 / 결산 / 예산',
    folder: '재무 & 회계 문서',
    isStarred: true,
    author: '재무회계팀 이영희',
    company: '주식회사 알파',
  },
  {
    id: 'doc-3',
    title: '표준 소프트웨어 개발 및 유지보수 용역계약서',
    fileName: 'Software_Development_Service_Agreement.docx',
    fileSize: 840000,
    format: 'docx',
    dateCreated: '2024-04-18',
    dateModified: '2024-04-19',
    pageCount: 8,
    thumbnailUrl: DocRendererService.generateDocumentFirstPageThumbnail(
      '표준 소프트웨어 개발 및 유지보수 용역계약서',
      'docx',
      '📜 계약서 / 법률',
      '발주자(갑)와 개발사(을) 간의 웹 애플리케이션 구축 및 1년간의 무상 유지보수, 지식재산권 귀속에 관한 법률 계약 문서입니다.',
      '2024-04-18',
      '법무팀'
    ),
    extractedText: '표준 소프트웨어 개발 및 유지보수 용역계약서\n제1조 [목적]\n본 계약은 발주사 주식회사 알파(이하 "갑")와 수급사 주식회사 베타(이하 "을") 간에 수행되는 Picasa 시스템 고도화 개발 용역의 범위와 조건을 정함에 있다.\n제2조 [용역 대금 및 지급 조건]\n총 계약금액은 금 이천일백구십만원(₩21,900,000)으로 하며, 계약금 30%, 중도금 40%, 검수 완료 후 잔금 30%를 지급한다.\n제3조 [비밀유지 및 지식재산권]\n본 용역의 결과물로 발생하는 모든 지식재산권 및 소스코드는 검수 완료 시점에 "갑"에게 완전히 귀속된다.',
    keywords: ['계약서', '소프트웨어', '용역계약', '지식재산권', '비밀유지', '하자보수', '을'],
    category: '📜 계약서 / 법률',
    folder: '법무 & 계약 체결',
    isStarred: false,
    author: '법무팀 박상무',
    company: '주식회사 알파',
  },
  {
    id: 'doc-4',
    title: '2024년도 정부지원 R&D 연구개발 최종결과보고서',
    fileName: '2024_Government_RND_Final_Report.hwp',
    fileSize: 6200000,
    format: 'hwp',
    dateCreated: '2024-05-30',
    dateModified: '2024-06-02',
    pageCount: 65,
    thumbnailUrl: DocRendererService.generateDocumentFirstPageThumbnail(
      '2024년도 정부지원 R&D 연구개발 최종결과보고서',
      'hwp',
      '🔬 연구 / 기술보고서',
      '중소벤처기업부 지원 과제인 "초고속 로컬 미디어 인덱싱 및 온디바이스 컴퓨터 비전 신경망 개발"에 대한 최종 정량적 성과 보고서입니다.',
      '2024-05-30',
      '기술연구소'
    ),
    extractedText: '2024년도 중소기업 기술혁신개발사업 최종보고서\n과제명: 브라우저 기반 대용량 미디어 인덱싱 및 AI 얼굴 특징 추출 파이프라인 개발\n주관연구기관: 주식회사 알파 기술연구소\n1. 연구개발 목표 달성도\n- 4K 이미지 렌더링 60fps 달성 (목표: 30fps)\n- 얼굴 인식 코사인 유사도 정확도 94.2% 달성\n- 10만 장 사진 1초 내 인덱싱 쿼리 응답 시간 검증 완료\n2. 특허 출원 및 논문 게재 실적: 국내 특허 2건 출원, KCI급 논문 1편 게재.',
    keywords: ['연구보고서', '정부지원사업', 'R&D', '특허출원', '컴퓨터비전', '인덱싱', '결과보고서'],
    category: '🔬 연구 / 기술보고서',
    folder: '정부 과제 & 공공 문서',
    isStarred: true,
    author: '기술연구소 홍수석',
    company: '주식회사 알파',
  },
  {
    id: 'doc-5',
    title: '2024년 3분기 IT 시스템 유지보수 견적서',
    fileName: '2024_Q3_System_Maintenance_Estimate.xlsx',
    fileSize: 920000,
    format: 'xlsx',
    dateCreated: '2024-08-02',
    dateModified: '2024-08-02',
    pageCount: 2,
    thumbnailUrl: DocRendererService.generateDocumentFirstPageThumbnail(
      '2024년 3분기 IT 시스템 유지보수 견적서',
      'xlsx',
      '📑 견적서 / 명세서',
      '고객사 서버 및 웹 애플리케이션의 정기 패치, 보안 취약점 점검 및 장애 대응 지원을 위한 3분기 유지보수 단가 견적서입니다.',
      '2024-08-02',
      '영업본부'
    ),
    extractedText: '견 적 서 (ESTIMATE)\n수신: 주식회사 감마 대표이사 귀하\n공급자: 주식회사 알파 (사업자등록번호: 120-88-00000)\n합계금액: 일천이백만원정 (₩12,000,000 / VAT 별도)\n세부 품목 내역:\n1. 클라우드 서버 24/7 모니터링: 1,500,000원 x 3개월\n2. 긴급 장애 복구 및 엔지니어 온사이트 지원: 1,000,000원 x 3회\n3. 데이터베이스 인덱스 최적화 및 보안 패치: 1,500,000원 x 3개월.',
    keywords: ['견적서', '유지보수', '공급가액', '단가', '합계금액', '서버관리', '견적'],
    category: '📑 견적서 / 명세서',
    folder: '영업 & 견적서',
    isStarred: false,
    author: '영업본부 최과장',
    company: '주식회사 알파',
  },
  {
    id: 'doc-6',
    title: '신규 입사자 표준 근로계약서 및 서약서',
    fileName: 'Standard_Employment_Contract_2024.docx',
    fileSize: 450000,
    format: 'docx',
    dateCreated: '2024-03-01',
    dateModified: '2024-03-05',
    pageCount: 4,
    thumbnailUrl: DocRendererService.generateDocumentFirstPageThumbnail(
      '신규 입사자 표준 근로계약서 및 서약서',
      'docx',
      '👥 인사 / 총무 / 행정',
      '근로기준법에 부합하는 정규직 근로조건, 소정근로시간, 연봉 산정 내역, 복리후생 및 정보보안 서약 조항이 포함된 문서입니다.',
      '2024-03-01',
      '인사총무팀'
    ),
    extractedText: '표준 근로계약서\n사업주(주식회사 알파)와 근로자는 상호 합의에 따라 다음과 같이 근로계약을 체결한다.\n1. 근로계약기간: 2024년 3월 1일부터 기한의 정함이 없음 (정규직)\n2. 근무장소 및 담당업무: 서울 본사 및 원격근무, 프론트엔드 소프트웨어 개발\n3. 소정근로시간: 1일 8시간 (주 40시간), 유연근무제 적용\n4. 임금: 기본급 및 식대 포함 연봉제 계약 체결.',
    keywords: ['근로계약서', '인사총무', '연봉제', '근로기준법', '보안서약서', '취업규칙'],
    category: '👥 인사 / 총무 / 행정',
    folder: '인사 & 총무 문서',
    isStarred: false,
    author: '인사팀 정팀장',
    company: '주식회사 알파',
  },
  {
    id: 'doc-7',
    title: '클라우드 네이티브 아키텍처 설계 가이드라인',
    fileName: 'Cloud_Native_Architecture_Guidelines.hwpx',
    fileSize: 3400000,
    format: 'hwpx',
    dateCreated: '2024-07-28',
    dateModified: '2024-08-01',
    pageCount: 30,
    thumbnailUrl: DocRendererService.generateDocumentFirstPageThumbnail(
      '클라우드 네이티브 아키텍처 설계 가이드라인',
      'hwpx',
      '🔬 연구 / 기술보고서',
      '마이크로서비스 아키텍처(MSA), 도커 컨테이너 오케스트레이션, 무중단 배포(CI/CD) 및 고가용성 DB 설계를 위한 표준 엔지니어링 지침서입니다.',
      '2024-07-28',
      '인프라개발실'
    ),
    extractedText: '클라우드 네이티브 시스템 아키텍처 표준 가이드라인 (HWPX)\n1. 아키텍처 설계 원칙\n- 마이크로서비스 간 느슨한 결합(Loose Coupling) 유지\n- 무상태성(Stateless) API 설계를 통한 탄력적 오토스케일링 보장\n- 데이터베이스 읽기/쓰기 분리(CQRS) 및 레디스 캐싱 레이어 적용\n2. 보안 및 네트워크 구성\n- 모든 내부 트래픽 mTLS 암호화 적용\n- IAM 기반 최소 권한 부여 원칙 준수.',
    keywords: ['아키텍처', '클라우드', '마이크로서비스', '도커', '가이드라인', '보안', 'HWPX'],
    category: '🔬 연구 / 기술보고서',
    folder: '기술 문서 & 아키텍처',
    isStarred: true,
    author: '인프라개발실 강이사',
    company: '주식회사 알파',
  },
  {
    id: 'doc-8',
    title: '인공지능 시대를 위한 차세대 소프트웨어 아키텍처',
    fileName: 'AI_Era_Software_Architecture_Guide.epub',
    fileSize: 5120000,
    format: 'epub',
    dateCreated: '2024-08-05',
    dateModified: '2024-08-08',
    pageCount: 328,
    thumbnailUrl: DocRendererService.generateDocumentFirstPageThumbnail(
      '인공지능 시대를 위한 차세대 소프트웨어 아키텍처',
      'epub',
      '📚 도서 / 전자책 (e-Book)',
      '온디바이스 AI, 고속 인덱싱 엔진, 이벤트 주도 분산 아키텍처의 설계 철학과 프로덕션 실전 구축 패턴을 총망라한 개발자 필독서입니다.',
      '2024-08-05',
      '공학박사 류승인'
    ),
    extractedText: '인공지능 시대를 위한 차세대 소프트웨어 아키텍처 (EPUB e-Book)\n저자: 류승인 | 출판: Picasa Publishing | 발행일: 2024년 8월\n[목차]\nChapter 1. 왜 온디바이스 인덱싱인가?\nChapter 2. Voidtools Everything 아키텍처의 비밀과 분산 색인\nChapter 3. Rust, WebAssembly, 그리고 브라우저 GPU 캔버스\nChapter 4. 로컬 퍼스트 소프트웨어의 미래와 프라이버시 보호\n\n[본문 발췌]\n인터넷 연결 없이도 내 컴퓨터의 수십만 개 문서를 0.05초 만에 검색하고 시각적으로 탐색할 수 있는 경험은 생산성의 새로운 지평을 엽니다.',
    keywords: ['전자책', 'epub', '소프트웨어', '아키텍처', '인공지능', '온디바이스', '출판사', '독서'],
    category: '📚 도서 / 전자책 (e-Book)',
    folder: '전자책 & 도서 라이브러리',
    isStarred: true,
    author: '류승인 박사',
    company: 'Picasa Digital Press',
  },
];
